# Generated by Django 5.0.3 on 2024-05-01 16:45

import creator.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0004_remove_media_uploaded_at_remove_media_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='file',
            field=models.FileField(upload_to=creator.helpers.get_upload_to),
        ),
    ]
