# Generated by Django 5.0.3 on 2024-05-04 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0005_alter_media_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='paypal_subscription_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], default='ACTIVE', max_length=10),
        ),
    ]
