# Generated by Django 5.0.3 on 2024-05-28 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0006_subscription_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tier',
            name='price',
        ),
        migrations.RemoveField(
            model_name='tier',
            name='stripe_price_id',
        ),
        migrations.RemoveField(
            model_name='tier',
            name='stripe_product_id',
        ),
        migrations.AddField(
            model_name='tier',
            name='points_price',
            field=models.IntegerField(default=100),
        ),
    ]
