# Generated by Django 5.0.3 on 2024-05-28 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0007_remove_tier_price_remove_tier_stripe_price_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tier',
            name='points_price',
            field=models.IntegerField(),
        ),
    ]
