# Generated by Django 5.0.3 on 2024-05-28 16:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0008_alter_tier_points_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='tier',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_tier_name_per_user'),
        ),
    ]
