# Generated by Django 5.0.3 on 2024-05-03 07:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('background_pic', models.ImageField(blank=True, null=True, upload_to='backgrounds/')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('website_url', models.URLField(blank=True, max_length=255, null=True, verbose_name='Website URL')),
                ('twitter_url', models.URLField(blank=True, max_length=255, null=True, verbose_name='Twitter URL')),
                ('instagram_url', models.URLField(blank=True, max_length=255, null=True, verbose_name='Instagram URL')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
