# Generated by Django 5.0.3 on 2024-05-05 07:49

import account.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_customuser_paypal_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='instagram_url',
            field=models.URLField(blank=True, max_length=255, null=True, validators=[account.validators.validate_instagram_url], verbose_name='Instagram URL'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='twitter_url',
            field=models.URLField(blank=True, max_length=255, null=True, validators=[account.validators.validate_twitter_url], verbose_name='Twitter URL'),
        ),
    ]
