# Generated by Django 5.0.3 on 2024-05-27 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_transaction_wallet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='paypal_email',
        ),
        migrations.AddField(
            model_name='customuser',
            name='stripe_account_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.IntegerField(default=0),
        ),
    ]
