# Generated by Django 5.0.3 on 2024-05-30 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='user',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
        migrations.DeleteModel(
            name='Wallet',
        ),
    ]
